export const GET_ITEMS_BY_FIRST_LETTER = 'REQUEST';
export const GET_ITEMS_BY_FIRST_LETTER_SUCCESS = 'REQUEST_SUCCESS';
export const GET_ITEMS_BY_FIRST_LETTER_FAIL = 'REQUEST_FAIL';

export const ON_SEARCH_INPUT_CHANGE = 'ON_SEARCH_INPUT_CHANGE';

export const CHANGE_SELECTED_PAGE = 'CHANGE_SELECTED_PAGE';

export const GET_ITEM_BY__ID = 'GET_ITEM_BY__ID';
export const GET_ITEM_BY__ID_SUCCESS = 'GET_ITEM_BY__ID_SUCCESS';
export const GET_ITEM_BY__ID_FAIL = 'GET_ITEM_BY__ID_FAIL';
